<a href="https://colab.research.google.com/github/Next-Generation-Data-Science/Coursework-1/blob/main/Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing packages
import pandas as pd

In [ ]:
# Reading the data
file_path = 'https://raw.githubusercontent.com/owid/covid-19-data/refs/heads/master/public/data/owid-covid-data.csv'
df = pd.read_csv(file_path)

In [ ]:
df.head(10)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
5,AFG,Asia,Afghanistan,2020-01-10,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
6,AFG,Asia,Afghanistan,2020-01-11,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
7,AFG,Asia,Afghanistan,2020-01-12,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
8,AFG,Asia,Afghanistan,2020-01-13,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
9,AFG,Asia,Afghanistan,2020-01-14,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 429435 entries, 0 to 429434
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    429435 non-null  object
 1   continent                                   402910 non-null  object
 2   location                                    429435 non-null  object
 3   date                                        429435 non-null  object
 4   total_cases                                 411804 non-null  float64
 5   new_cases                                   410159 non-null  float64
 6   new_cases_smoothed                          408929 non-null  float64
 7   total_deaths                                411804 non-null  float64
 8   new_deaths                                  410608 non-null  float64
 9   new_deaths_smoothed                         409378 non-null  float64
 10  total_cases_per_million                     411804 non-null  float64
 11  new_cases_per_million                       410159 non-null  float64
 12  new_cases_smoothed_per_million              408929 non-null  float64
 13  total_deaths_per_million                    411804 non-null  float64
 14  new_deaths_per_million                      410608 non-null  float64
 15  new_deaths_smoothed_per_million             409378 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                39116 non-null   float64
 18  icu_patients_per_million                    39116 non-null   float64
 19  hosp_patients                               40656 non-null   float64
 20  hosp_patients_per_million                   40656 non-null   float64
 21  weekly_icu_admissions                       10993 non-null   float64
 22  weekly_icu_admissions_per_million           10993 non-null   float64
 23  weekly_hosp_admissions                      24497 non-null   float64
 24  weekly_hosp_admissions_per_million          24497 non-null   float64
 25  total_tests                                 79387 non-null   float64
 26  new_tests                                   75403 non-null   float64
 27  total_tests_per_thousand                    79387 non-null   float64
 28  new_tests_per_thousand                      75403 non-null   float64
 29  new_tests_smoothed                          103965 non-null  float64
 30  new_tests_smoothed_per_thousand             103965 non-null  float64
 31  positive_rate                               95927 non-null   float64
 32  tests_per_case                              94348 non-null   float64
 33  tests_units                                 106788 non-null  object
 34  total_vaccinations                          85417 non-null   float64
 35  people_vaccinated                           81132 non-null   float64
 36  people_fully_vaccinated                     78061 non-null   float64
 37  total_boosters                              53600 non-null   float64
 38  new_vaccinations                            70971 non-null   float64
 39  new_vaccinations_smoothed                   195029 non-null  float64
 40  total_vaccinations_per_hundred              85417 non-null   float64
 41  people_vaccinated_per_hundred               81132 non-null   float64
 42  people_fully_vaccinated_per_hundred         78061 non-null   float64
 43  total_boosters_per_hundred                  53600 non-null   float64
 44  new_vaccinations_smoothed_per_million       195029 non-null  float64
 45  new_people_vaccinated_smoothed              192177 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  192177 non-null  float64
 47  stringency_index                            196190 non-null  float64
 48  population_density                          360492 non-null  float64
 49  median_age                                  334663 non-null  float64
 50  aged_65_older                               323270 non-null  float64
 51  aged_70_older                               331315 non-null  float64
 52  gdp_per_capita                              328292 non-null  float64
 53  extreme_poverty                             211996 non-null  float64
 54  cardiovasc_death_rate                       328865 non-null  float64
 55  diabetes_prevalence                         345911 non-null  float64
 56  female_smokers                              247165 non-null  float64
 57  male_smokers                                243817 non-null  float64
 58  handwashing_facilities                      161741 non-null  float64
 59  hospital_beds_per_thousand                  290689 non-null  float64
 60  life_expectancy                             390299 non-null  float64
 61  human_development_index                     319127 non-null  float64
 62  population                                  429435 non-null  int64
 63  excess_mortality_cumulative_absolute        13411 non-null   float64
 64  excess_mortality_cumulative                 13411 non-null   float64
 65  excess_mortality                            13411 non-null   float64
 66  excess_mortality_cumulative_per_million     13411 non-null   float64
dtypes: float64(61), int64(1), object(5)
memory usage: 219.5+ MB

In [ ]:
df.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,4.118040e+05,4.101590e+05,4.089290e+05,4.118040e+05,410608.000000,409378.000000,411804.000000,410159.000000,408929.000000,411804.000000,...,243817.000000,161741.000000,290689.000000,390299.000000,319127.000000,4.294350e+05,1.341100e+04,13411.000000,13411.000000,13411.000000
mean,7.365292e+06,8.017360e+03,8.041026e+03,8.125957e+04,71.852139,72.060828,112096.199420,122.357073,122.713852,835.514337,...,33.097758,50.649390,3.106895,73.702098,0.722178,1.520336e+08,5.604765e+04,9.766431,10.925353,1772.666404
std,4.477582e+07,2.296649e+05,8.661611e+04,4.411901e+05,1368.322990,513.636565,162240.412405,1508.778585,559.701663,1134.932641,...,13.853952,31.905236,2.549168,7.387914,0.149237,6.975408e+08,1.568691e+05,12.040658,24.560706,1991.892770
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,7.700000,1.190000,0.100000,53.280000,0.390000,4.700000e+01,-3.772610e+04,-44.230000,-95.920000,-2936.450000
25%,6.280750e+03,0.000000e+00,0.000000e+00,4.300000e+01,0.000000,0.000000,1916.100000,0.000000,0.000000,24.570000,...,22.600000,20.860000,1.300000,69.500000,0.600000,5.237980e+05,1.765000e+02,2.060000,-1.500000,116.875000
50%,6.365300e+04,0.000000e+00,1.200000e+01,7.990000e+02,0.000000,0.000000,29145.480000,0.000000,2.790000,295.090000,...,33.100000,49.540000,2.500000,75.050000,0.740000,6.336393e+06,6.815200e+03,8.130000,5.660000,1270.800000
75%,7.582720e+05,0.000000e+00,3.132900e+02,9.574000e+03,0.000000,3.140000,156770.190000,0.000000,56.250000,1283.820000,...,41.500000,82.500000,4.210000,79.460000,0.830000,3.296952e+07,3.912804e+04,15.160000,15.575000,2883.025000
max,7.758668e+08,4.423623e+07,6.319461e+06,7.057132e+06,103719.000000,14817.000000,763598.600000,241758.230000,34536.890000,6601.110000,...,78.100000,100.000000,13.800000,86.750000,0.960000,7.975105e+09,1.349776e+06,78.080000,378.220000,10293.520000

In [ ]:
# Find the minimum and maximum date
min_date = df['date'].min()
max_date = df['date'].max()

# Print the range
print(f"Date range: {min_date} to {max_date}")

Date range: 2020-01-01 to 2024-08-14

In [ ]:
## CLEANING & PREPROCESSING FUNCTION

# Function to selected desired columns and remove any NaNs
def cleaning_data(df):

  # Keep only the columns specified by index
  #small_df = df.iloc[:, list(range(0,6)) + [7, 8, 17, 19, 25, 26] + list(range(31,39)) + list(range(49,59)) + [60, 61, 62, 65]]
  small_df = df.iloc[:, list(range(0,6)) + [7, 8, 17, 19, 25, 26] + list(range(31,39)) + [62]]

  # Removing any NaNs
  cleaned_df = small_df.dropna().copy()

  # Convert 'date' column to datetime format
  cleaned_df['date'] = pd.to_datetime(cleaned_df['date'])

  # Return the cleaned dataframe
  return cleaned_df

cleaned_df = cleaning_data(df)

In [ ]:
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5027 entries, 22417 to 404346
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   iso_code                 5027 non-null   object
 1   continent                5027 non-null   object
 2   location                 5027 non-null   object
 3   date                     5027 non-null   datetime64[ns]
 4   total_cases              5027 non-null   float64
 5   new_cases                5027 non-null   float64
 6   total_deaths             5027 non-null   float64
 7   new_deaths               5027 non-null   float64
 8   icu_patients             5027 non-null   float64
 9   hosp_patients            5027 non-null   float64
 10  total_tests              5027 non-null   float64
 11  new_tests                5027 non-null   float64
 12  positive_rate            5027 non-null   float64
 13  tests_per_case           5027 non-null   float64
 14  tests_units              5027 non-null   object
 15  total_vaccinations       5027 non-null   float64
 16  people_vaccinated        5027 non-null   float64
 17  people_fully_vaccinated  5027 non-null   float64
 18  total_boosters           5027 non-null   float64
 19  new_vaccinations         5027 non-null   float64
 20  population               5027 non-null   int64
dtypes: datetime64[ns](1), float64(15), int64(1), object(4)
memory usage: 864.0+ KB

In [ ]:
cleaned_df.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'total_deaths', 'new_deaths', 'icu_patients', 'hosp_patients',
       'total_tests', 'new_tests', 'positive_rate', 'tests_per_case',
       'tests_units', 'total_vaccinations', 'people_vaccinated',
       'people_fully_vaccinated', 'total_boosters', 'new_vaccinations',
       'population'],
      dtype='object')

In [ ]:
cleaned_df.describe()

,date,total_cases,new_cases,total_deaths,new_deaths,icu_patients,hosp_patients,total_tests,new_tests,positive_rate,tests_per_case,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,population
count,5027,5.027000e+03,5.027000e+03,5.027000e+03,5027.000000,5027.000000,5027.000000,5.027000e+03,5.027000e+03,5027.000000,5027.000000,5.027000e+03,5.027000e+03,5.027000e+03,5.027000e+03,5.027000e+03,5.027000e+03
mean,2021-11-21 23:09:52.241893888,8.788469e+06,2.703229e+04,1.179065e+05,159.448976,1654.287647,9243.643923,1.247929e+08,2.840925e+05,0.112672,38.765924,7.929195e+07,3.738382e+07,3.248358e+07,1.069629e+07,2.076967e+05,5.960455e+07
min,2021-01-10 00:00:00,3.901600e+04,0.000000e+00,3.570000e+02,0.000000,0.000000,15.000000,6.851650e+05,1.360000e+02,0.000000,1.300000,1.091900e+04,1.091600e+04,3.340000e+02,1.000000e+00,1.000000e+00,6.476010e+05
25%,2021-08-22 12:00:00,1.033610e+06,0.000000e+00,1.002400e+04,0.000000,99.000000,680.500000,1.601278e+07,2.367250e+04,0.040000,6.400000,9.681206e+06,5.433298e+06,3.761386e+06,8.797000e+03,1.009850e+04,1.049399e+07
50%,2021-12-07 00:00:00,2.649770e+06,0.000000e+00,3.002600e+04,0.000000,310.000000,2433.000000,4.246902e+07,9.240100e+04,0.070000,14.400000,2.499816e+07,9.244009e+06,8.905587e+06,1.208408e+06,5.233400e+04,2.617741e+07
75%,2022-03-08 00:00:00,6.267035e+06,0.000000e+00,1.187935e+05,0.000000,989.500000,9238.500000,1.129845e+08,3.202970e+05,0.160000,28.200000,9.221908e+07,4.728664e+07,4.294118e+07,8.272406e+06,1.960065e+05,6.750894e+07
max,2022-06-22 00:00:00,8.458854e+07,5.650933e+06,1.002709e+06,20100.000000,26458.000000,154497.000000,9.127691e+08,3.201706e+06,0.750000,1000.000000,5.974298e+08,2.593552e+08,2.231962e+08,1.240619e+08,4.581777e+06,3.382899e+08
std,NaN,1.614311e+07,1.882373e+05,2.190151e+05,1119.725254,4095.371049,18079.929586,1.988069e+08,4.469016e+05,0.111947,99.633937,1.275207e+08,6.065691e+07,5.263698e+07,2.174115e+07,4.477487e+05,9.570860e+07

In [ ]:
cleaned_df['tests_units'].unique()

array(['tests performed', 'people tested'], dtype=object)

In [ ]:
# Find the minimum and maximum date
min_date = cleaned_df['date'].min()
max_date = cleaned_df['date'].max()

# Print the range
print(f"Date range: {min_date} to {max_date}")

Date range: 2021-01-10 00:00:00 to 2022-06-22 00:00:00